// <auto-generated />
using System;
using Covid19_Tracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAB_HANDIN_2.Migrations
{
    [DbContext(typeof(CovidContext))]
    [Migration("20201117093553_initialcommit")]
    partial class initialcommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Covid19_Tracking.Domain.Citizen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MunicipalityID")
                        .HasColumnType("int");

                    b.Property<string>("SSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MunicipalityID");

                    b.ToTable("Citizens");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Age = 11,
                            FirstName = "Henrik",
                            LastName = "Hansen",
                            MunicipalityID = 751,
                            SSN = "201209-9154",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 2,
                            Age = 85,
                            FirstName = "Lene",
                            LastName = "Mortensen",
                            MunicipalityID = 751,
                            SSN = "230735-2189",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 3,
                            Age = 38,
                            FirstName = "Hans",
                            LastName = "Larsen",
                            MunicipalityID = 751,
                            SSN = "100282-0686",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 4,
                            Age = 17,
                            FirstName = "Hans",
                            LastName = "Mortensen",
                            MunicipalityID = 751,
                            SSN = "200503-1945",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 5,
                            Age = 14,
                            FirstName = "Lise",
                            LastName = "Frederiksen",
                            MunicipalityID = 751,
                            SSN = "151006-5513",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 6,
                            Age = 83,
                            FirstName = "Hans",
                            LastName = "Olsen",
                            MunicipalityID = 751,
                            SSN = "020637-9743",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 7,
                            Age = 47,
                            FirstName = "Mette",
                            LastName = "Hansen",
                            MunicipalityID = 751,
                            SSN = "250273-3438",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 8,
                            Age = 1,
                            FirstName = "Morten",
                            LastName = "Olsen",
                            MunicipalityID = 751,
                            SSN = "160819-2120",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 9,
                            Age = 0,
                            FirstName = "Bob",
                            LastName = "Mortensen",
                            MunicipalityID = 751,
                            SSN = "180920-7789",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 10,
                            Age = 29,
                            FirstName = "Lene",
                            LastName = "Olsen",
                            MunicipalityID = 751,
                            SSN = "210991-9650",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 11,
                            Age = 28,
                            FirstName = "Alice",
                            LastName = "Frederiksen",
                            MunicipalityID = 751,
                            SSN = "180292-3819",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 12,
                            Age = 80,
                            FirstName = "Alice",
                            LastName = "Jensen",
                            MunicipalityID = 751,
                            SSN = "071140-6096",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 13,
                            Age = 98,
                            FirstName = "Alice",
                            LastName = "Olsen",
                            MunicipalityID = 751,
                            SSN = "040522-4917",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 14,
                            Age = 43,
                            FirstName = "Hanne",
                            LastName = "Olsen",
                            MunicipalityID = 751,
                            SSN = "210377-8834",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 15,
                            Age = 15,
                            FirstName = "Mette",
                            LastName = "Olsen",
                            MunicipalityID = 751,
                            SSN = "140505-8822",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 16,
                            Age = 91,
                            FirstName = "Bob",
                            LastName = "Larsen",
                            MunicipalityID = 751,
                            SSN = "161029-0902",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 17,
                            Age = 38,
                            FirstName = "Morten",
                            LastName = "Jensen",
                            MunicipalityID = 751,
                            SSN = "250382-2831",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 18,
                            Age = 58,
                            FirstName = "Jens",
                            LastName = "Mortensen",
                            MunicipalityID = 751,
                            SSN = "100662-6508",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 19,
                            Age = 87,
                            FirstName = "Mathias",
                            LastName = "Frederiksen",
                            MunicipalityID = 751,
                            SSN = "260633-8511",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 20,
                            Age = 76,
                            FirstName = "Hanne",
                            LastName = "Mortensen",
                            MunicipalityID = 751,
                            SSN = "140944-8894",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 21,
                            Age = 57,
                            FirstName = "Alice",
                            LastName = "Olsen",
                            MunicipalityID = 751,
                            SSN = "150563-4848",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 22,
                            Age = 87,
                            FirstName = "Jens",
                            LastName = "Mortensen",
                            MunicipalityID = 751,
                            SSN = "010833-4669",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 23,
                            Age = 14,
                            FirstName = "Hanne",
                            LastName = "Larsen",
                            MunicipalityID = 751,
                            SSN = "260306-1597",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 24,
                            Age = 66,
                            FirstName = "Jens",
                            LastName = "Larsen",
                            MunicipalityID = 751,
                            SSN = "100354-5700",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 25,
                            Age = 39,
                            FirstName = "Lene",
                            LastName = "Mortensen",
                            MunicipalityID = 751,
                            SSN = "130581-6589",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 26,
                            Age = 81,
                            FirstName = "Henrik",
                            LastName = "Jensen",
                            MunicipalityID = 101,
                            SSN = "030239-2849",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 27,
                            Age = 87,
                            FirstName = "Jens",
                            LastName = "Frederiksen",
                            MunicipalityID = 101,
                            SSN = "260533-9722",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 28,
                            Age = 56,
                            FirstName = "Mette",
                            LastName = "Hansen",
                            MunicipalityID = 101,
                            SSN = "140964-3558",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 29,
                            Age = 17,
                            FirstName = "Alice",
                            LastName = "Hansen",
                            MunicipalityID = 101,
                            SSN = "051103-4086",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 30,
                            Age = 58,
                            FirstName = "Jens",
                            LastName = "Olsen",
                            MunicipalityID = 101,
                            SSN = "061062-6328",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 31,
                            Age = 83,
                            FirstName = "Mette",
                            LastName = "Mortensen",
                            MunicipalityID = 101,
                            SSN = "021137-0508",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 32,
                            Age = 43,
                            FirstName = "Hans",
                            LastName = "Hansen",
                            MunicipalityID = 101,
                            SSN = "240877-0805",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 33,
                            Age = 94,
                            FirstName = "Mathias",
                            LastName = "Larsen",
                            MunicipalityID = 101,
                            SSN = "190426-6611",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 34,
                            Age = 90,
                            FirstName = "Henrik",
                            LastName = "Hansen",
                            MunicipalityID = 101,
                            SSN = "081130-0002",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 35,
                            Age = 69,
                            FirstName = "Morten",
                            LastName = "Mortensen",
                            MunicipalityID = 101,
                            SSN = "170551-0100",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 36,
                            Age = 43,
                            FirstName = "Alice",
                            LastName = "Jensen",
                            MunicipalityID = 101,
                            SSN = "240477-4467",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 37,
                            Age = 30,
                            FirstName = "Lise",
                            LastName = "Hansen",
                            MunicipalityID = 101,
                            SSN = "090490-6312",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 38,
                            Age = 54,
                            FirstName = "Mathias",
                            LastName = "Mortensen",
                            MunicipalityID = 101,
                            SSN = "151266-4158",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 39,
                            Age = 81,
                            FirstName = "Alice",
                            LastName = "Frederiksen",
                            MunicipalityID = 101,
                            SSN = "280139-6939",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 40,
                            Age = 27,
                            FirstName = "Alice",
                            LastName = "Mortensen",
                            MunicipalityID = 101,
                            SSN = "080193-9200",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 41,
                            Age = 80,
                            FirstName = "Mette",
                            LastName = "Hansen",
                            MunicipalityID = 101,
                            SSN = "280340-2357",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 42,
                            Age = 93,
                            FirstName = "Lise",
                            LastName = "Larsen",
                            MunicipalityID = 101,
                            SSN = "160527-9487",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 43,
                            Age = 7,
                            FirstName = "Lise",
                            LastName = "Mortensen",
                            MunicipalityID = 101,
                            SSN = "110813-0713",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 44,
                            Age = 85,
                            FirstName = "Mette",
                            LastName = "Frederiksen",
                            MunicipalityID = 101,
                            SSN = "081035-4520",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 45,
                            Age = 5,
                            FirstName = "Bob",
                            LastName = "Hansen",
                            MunicipalityID = 101,
                            SSN = "080915-7389",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 46,
                            Age = 50,
                            FirstName = "Bob",
                            LastName = "Hansen",
                            MunicipalityID = 101,
                            SSN = "220370-4840",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 47,
                            Age = 45,
                            FirstName = "Hanne",
                            LastName = "Jensen",
                            MunicipalityID = 101,
                            SSN = "200975-6615",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 48,
                            Age = 89,
                            FirstName = "Lise",
                            LastName = "Mortensen",
                            MunicipalityID = 101,
                            SSN = "141131-0659",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 49,
                            Age = 74,
                            FirstName = "Jesper",
                            LastName = "Larsen",
                            MunicipalityID = 101,
                            SSN = "131046-3640",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 50,
                            Age = 29,
                            FirstName = "Lise",
                            LastName = "Mortensen",
                            MunicipalityID = 101,
                            SSN = "190391-3178",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 51,
                            Age = 61,
                            FirstName = "Alice",
                            LastName = "Olsen",
                            MunicipalityID = 740,
                            SSN = "120859-8434",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 52,
                            Age = 57,
                            FirstName = "Alice",
                            LastName = "Frederiksen",
                            MunicipalityID = 740,
                            SSN = "011063-7581",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 53,
                            Age = 78,
                            FirstName = "Mathias",
                            LastName = "Frederiksen",
                            MunicipalityID = 740,
                            SSN = "250942-2588",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 54,
                            Age = 29,
                            FirstName = "Henrik",
                            LastName = "Frederiksen",
                            MunicipalityID = 740,
                            SSN = "120291-8868",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 55,
                            Age = 2,
                            FirstName = "Lene",
                            LastName = "Hansen",
                            MunicipalityID = 740,
                            SSN = "150518-3294",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 56,
                            Age = 6,
                            FirstName = "Henrik",
                            LastName = "Mortensen",
                            MunicipalityID = 740,
                            SSN = "080314-8040",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 57,
                            Age = 45,
                            FirstName = "Henrik",
                            LastName = "Mortensen",
                            MunicipalityID = 740,
                            SSN = "280875-4848",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 58,
                            Age = 79,
                            FirstName = "Lene",
                            LastName = "Frederiksen",
                            MunicipalityID = 740,
                            SSN = "160141-3010",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 59,
                            Age = 1,
                            FirstName = "Mette",
                            LastName = "Frederiksen",
                            MunicipalityID = 740,
                            SSN = "141219-7378",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 60,
                            Age = 47,
                            FirstName = "Lene",
                            LastName = "Jensen",
                            MunicipalityID = 740,
                            SSN = "130673-2333",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 61,
                            Age = 60,
                            FirstName = "Henrik",
                            LastName = "Larsen",
                            MunicipalityID = 740,
                            SSN = "130660-0632",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 62,
                            Age = 40,
                            FirstName = "Jesper",
                            LastName = "Mortensen",
                            MunicipalityID = 740,
                            SSN = "150580-9963",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 63,
                            Age = 99,
                            FirstName = "Jesper",
                            LastName = "Mortensen",
                            MunicipalityID = 740,
                            SSN = "080121-5419",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 64,
                            Age = 79,
                            FirstName = "Hanne",
                            LastName = "Larsen",
                            MunicipalityID = 740,
                            SSN = "080141-4287",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 65,
                            Age = 54,
                            FirstName = "Jesper",
                            LastName = "Mortensen",
                            MunicipalityID = 740,
                            SSN = "050466-5745",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 66,
                            Age = 8,
                            FirstName = "Hanne",
                            LastName = "Frederiksen",
                            MunicipalityID = 740,
                            SSN = "170312-3999",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 67,
                            Age = 95,
                            FirstName = "Henrik",
                            LastName = "Olsen",
                            MunicipalityID = 740,
                            SSN = "160925-4371",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 68,
                            Age = 16,
                            FirstName = "Bob",
                            LastName = "Jensen",
                            MunicipalityID = 740,
                            SSN = "120904-3356",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 69,
                            Age = 18,
                            FirstName = "Lise",
                            LastName = "Frederiksen",
                            MunicipalityID = 740,
                            SSN = "110802-9350",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 70,
                            Age = 33,
                            FirstName = "Lise",
                            LastName = "Larsen",
                            MunicipalityID = 740,
                            SSN = "050687-4750",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 71,
                            Age = 68,
                            FirstName = "Lise",
                            LastName = "Hansen",
                            MunicipalityID = 740,
                            SSN = "230252-6329",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 72,
                            Age = 71,
                            FirstName = "Alice",
                            LastName = "Olsen",
                            MunicipalityID = 740,
                            SSN = "101249-7038",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 73,
                            Age = 77,
                            FirstName = "Jesper",
                            LastName = "Mortensen",
                            MunicipalityID = 740,
                            SSN = "160343-8991",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 74,
                            Age = 21,
                            FirstName = "Jens",
                            LastName = "Olsen",
                            MunicipalityID = 740,
                            SSN = "170699-2395",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 75,
                            Age = 40,
                            FirstName = "Bob",
                            LastName = "Frederiksen",
                            MunicipalityID = 740,
                            SSN = "091280-7353",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 76,
                            Age = 60,
                            FirstName = "Jesper",
                            LastName = "Mortensen",
                            MunicipalityID = 851,
                            SSN = "160960-4286",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 77,
                            Age = 6,
                            FirstName = "Jesper",
                            LastName = "Larsen",
                            MunicipalityID = 851,
                            SSN = "190314-6674",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 78,
                            Age = 59,
                            FirstName = "Morten",
                            LastName = "Olsen",
                            MunicipalityID = 851,
                            SSN = "060761-7447",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 79,
                            Age = 18,
                            FirstName = "Mette",
                            LastName = "Hansen",
                            MunicipalityID = 851,
                            SSN = "190502-8797",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 80,
                            Age = 0,
                            FirstName = "Mette",
                            LastName = "Jensen",
                            MunicipalityID = 851,
                            SSN = "011220-0166",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 81,
                            Age = 1,
                            FirstName = "Lise",
                            LastName = "Larsen",
                            MunicipalityID = 851,
                            SSN = "160619-8717",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 82,
                            Age = 96,
                            FirstName = "Mathias",
                            LastName = "Olsen",
                            MunicipalityID = 851,
                            SSN = "070724-2622",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 83,
                            Age = 13,
                            FirstName = "Jesper",
                            LastName = "Hansen",
                            MunicipalityID = 851,
                            SSN = "111207-6379",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 84,
                            Age = 87,
                            FirstName = "Bob",
                            LastName = "Hansen",
                            MunicipalityID = 851,
                            SSN = "090733-5712",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 85,
                            Age = 61,
                            FirstName = "Lene",
                            LastName = "Jensen",
                            MunicipalityID = 851,
                            SSN = "080859-4024",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 86,
                            Age = 64,
                            FirstName = "Bob",
                            LastName = "Olsen",
                            MunicipalityID = 851,
                            SSN = "031156-2270",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 87,
                            Age = 44,
                            FirstName = "Bob",
                            LastName = "Jensen",
                            MunicipalityID = 851,
                            SSN = "230876-3875",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 88,
                            Age = 64,
                            FirstName = "Henrik",
                            LastName = "Olsen",
                            MunicipalityID = 851,
                            SSN = "280556-3992",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 89,
                            Age = 22,
                            FirstName = "Lise",
                            LastName = "Frederiksen",
                            MunicipalityID = 851,
                            SSN = "260498-6785",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 90,
                            Age = 97,
                            FirstName = "Jesper",
                            LastName = "Hansen",
                            MunicipalityID = 851,
                            SSN = "261123-7154",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 91,
                            Age = 28,
                            FirstName = "Mette",
                            LastName = "Jensen",
                            MunicipalityID = 851,
                            SSN = "040592-9658",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 92,
                            Age = 48,
                            FirstName = "Lene",
                            LastName = "Jensen",
                            MunicipalityID = 851,
                            SSN = "270372-5739",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 93,
                            Age = 28,
                            FirstName = "Mette",
                            LastName = "Jensen",
                            MunicipalityID = 851,
                            SSN = "080192-6842",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 94,
                            Age = 18,
                            FirstName = "Mette",
                            LastName = "Olsen",
                            MunicipalityID = 851,
                            SSN = "170702-3222",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 95,
                            Age = 89,
                            FirstName = "Henrik",
                            LastName = "Larsen",
                            MunicipalityID = 851,
                            SSN = "220931-5049",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 96,
                            Age = 86,
                            FirstName = "Jesper",
                            LastName = "Olsen",
                            MunicipalityID = 851,
                            SSN = "280634-1809",
                            Sex = "male"
                        },
                        new
                        {
                            ID = 97,
                            Age = 99,
                            FirstName = "Bob",
                            LastName = "Frederiksen",
                            MunicipalityID = 851,
                            SSN = "040221-5872",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 98,
                            Age = 64,
                            FirstName = "Lise",
                            LastName = "Olsen",
                            MunicipalityID = 851,
                            SSN = "240156-0145",
                            Sex = "either"
                        },
                        new
                        {
                            ID = 99,
                            Age = 54,
                            FirstName = "Hanne",
                            LastName = "Hansen",
                            MunicipalityID = 851,
                            SSN = "250866-4855",
                            Sex = "female"
                        },
                        new
                        {
                            ID = 100,
                            Age = 17,
                            FirstName = "Morten",
                            LastName = "Larsen",
                            MunicipalityID = 851,
                            SSN = "150103-4148",
                            Sex = "male"
                        });
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.CitizenLocation", b =>
                {
                    b.Property<int>("CitizenLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Citizen_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("CitizenLocationId");

                    b.HasIndex("Adresse");

                    b.HasIndex("Citizen_ID");

                    b.ToTable("CitizenLocations");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.Location", b =>
                {
                    b.Property<string>("Addresse")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MunicipalityID")
                        .HasColumnType("int");

                    b.HasKey("Addresse");

                    b.HasIndex("MunicipalityID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Addresse = "Århus vænget"
                        },
                        new
                        {
                            Addresse = "Århus skadevej"
                        },
                        new
                        {
                            Addresse = "Skejby gade"
                        });
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.Municipality", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationId")
                        .HasColumnType("int");

                    b.Property<string>("Nation_Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Nation_Name");

                    b.ToTable("Municipalities");

                    b.HasData(
                        new
                        {
                            ID = 101,
                            Name = "København",
                            NationId = 0,
                            Population = 632340
                        },
                        new
                        {
                            ID = 147,
                            Name = "Frederiksberg",
                            NationId = 0,
                            Population = 104305
                        },
                        new
                        {
                            ID = 151,
                            Name = "Ballerup",
                            NationId = 0,
                            Population = 48602
                        },
                        new
                        {
                            ID = 153,
                            Name = "Brøndby",
                            NationId = 0,
                            Population = 35090
                        },
                        new
                        {
                            ID = 155,
                            Name = "Dragør",
                            NationId = 0,
                            Population = 14494
                        },
                        new
                        {
                            ID = 157,
                            Name = "Gentofte",
                            NationId = 0,
                            Population = 74830
                        },
                        new
                        {
                            ID = 159,
                            Name = "Gladsaxe",
                            NationId = 0,
                            Population = 69262
                        },
                        new
                        {
                            ID = 161,
                            Name = "Glostrup",
                            NationId = 0,
                            Population = 23128
                        },
                        new
                        {
                            ID = 163,
                            Name = "Herlev",
                            NationId = 0,
                            Population = 28953
                        },
                        new
                        {
                            ID = 165,
                            Name = "Albertslund",
                            NationId = 0,
                            Population = 27731
                        },
                        new
                        {
                            ID = 167,
                            Name = "Hvidovre",
                            NationId = 0,
                            Population = 53527
                        },
                        new
                        {
                            ID = 169,
                            Name = "Høje-Taastrup",
                            NationId = 0,
                            Population = 50759
                        },
                        new
                        {
                            ID = 173,
                            Name = "Lyngby-Taarbæk",
                            NationId = 0,
                            Population = 56214
                        },
                        new
                        {
                            ID = 175,
                            Name = "Rødovre",
                            NationId = 0,
                            Population = 40652
                        },
                        new
                        {
                            ID = 183,
                            Name = "Ishøj",
                            NationId = 0,
                            Population = 22989
                        },
                        new
                        {
                            ID = 185,
                            Name = "Tårnby",
                            NationId = 0,
                            Population = 42989
                        },
                        new
                        {
                            ID = 187,
                            Name = "Vallensbæk",
                            NationId = 0,
                            Population = 16633
                        },
                        new
                        {
                            ID = 190,
                            Name = "Furesø",
                            NationId = 0,
                            Population = 40965
                        },
                        new
                        {
                            ID = 201,
                            Name = "Allerød",
                            NationId = 0,
                            Population = 25633
                        },
                        new
                        {
                            ID = 210,
                            Name = "Fredensborg",
                            NationId = 0,
                            Population = 40865
                        },
                        new
                        {
                            ID = 217,
                            Name = "Helsingør",
                            NationId = 0,
                            Population = 62695
                        },
                        new
                        {
                            ID = 219,
                            Name = "Hillerød",
                            NationId = 0,
                            Population = 51183
                        },
                        new
                        {
                            ID = 223,
                            Name = "Hørsholm",
                            NationId = 0,
                            Population = 24864
                        },
                        new
                        {
                            ID = 230,
                            Name = "Rudersdal",
                            NationId = 0,
                            Population = 56728
                        },
                        new
                        {
                            ID = 240,
                            Name = "Egedal",
                            NationId = 0,
                            Population = 43354
                        },
                        new
                        {
                            ID = 250,
                            Name = "Frederikssund",
                            NationId = 0,
                            Population = 45223
                        },
                        new
                        {
                            ID = 253,
                            Name = "Greve",
                            NationId = 0,
                            Population = 50558
                        },
                        new
                        {
                            ID = 259,
                            Name = "Køge",
                            NationId = 0,
                            Population = 60979
                        },
                        new
                        {
                            ID = 260,
                            Name = "Halsnæs",
                            NationId = 0,
                            Population = 31384
                        },
                        new
                        {
                            ID = 265,
                            Name = "Roskilde",
                            NationId = 0,
                            Population = 87914
                        },
                        new
                        {
                            ID = 269,
                            Name = "Solrød",
                            NationId = 0,
                            Population = 23255
                        },
                        new
                        {
                            ID = 270,
                            Name = "Gribskov",
                            NationId = 0,
                            Population = 41048
                        },
                        new
                        {
                            ID = 306,
                            Name = "Odsherred",
                            NationId = 0,
                            Population = 32957
                        },
                        new
                        {
                            ID = 316,
                            Name = "Holbæk",
                            NationId = 0,
                            Population = 71541
                        },
                        new
                        {
                            ID = 320,
                            Name = "Faxe",
                            NationId = 0,
                            Population = 36576
                        },
                        new
                        {
                            ID = 326,
                            Name = "Kalundborg",
                            NationId = 0,
                            Population = 48436
                        },
                        new
                        {
                            ID = 329,
                            Name = "Ringsted",
                            NationId = 0,
                            Population = 34852
                        },
                        new
                        {
                            ID = 330,
                            Name = "Slagelse",
                            NationId = 0,
                            Population = 79073
                        },
                        new
                        {
                            ID = 336,
                            Name = "Stevns",
                            NationId = 0,
                            Population = 22805
                        },
                        new
                        {
                            ID = 340,
                            Name = "Sorø",
                            NationId = 0,
                            Population = 29881
                        },
                        new
                        {
                            ID = 350,
                            Name = "Lejre",
                            NationId = 0,
                            Population = 27996
                        },
                        new
                        {
                            ID = 360,
                            Name = "Lolland",
                            NationId = 0,
                            Population = 41105
                        },
                        new
                        {
                            ID = 370,
                            Name = "Næstved",
                            NationId = 0,
                            Population = 83143
                        },
                        new
                        {
                            ID = 376,
                            Name = "Guldborgsund",
                            NationId = 0,
                            Population = 60722
                        },
                        new
                        {
                            ID = 390,
                            Name = "Vordingborg",
                            NationId = 0,
                            Population = 45566
                        },
                        new
                        {
                            ID = 400,
                            Name = "Bornholm",
                            NationId = 0,
                            Population = 39499
                        },
                        new
                        {
                            ID = 410,
                            Name = "Middelfart",
                            NationId = 0,
                            Population = 38853
                        },
                        new
                        {
                            ID = 411,
                            Name = "Christiansø",
                            NationId = 0,
                            Population = 84000
                        },
                        new
                        {
                            ID = 420,
                            Name = "Assens",
                            NationId = 0,
                            Population = 40965
                        },
                        new
                        {
                            ID = 430,
                            Name = "Faaborg-Midtfyn",
                            NationId = 0,
                            Population = 51556
                        },
                        new
                        {
                            ID = 440,
                            Name = "Kerteminde",
                            NationId = 0,
                            Population = 23812
                        },
                        new
                        {
                            ID = 450,
                            Name = "Nyborg",
                            NationId = 0,
                            Population = 32009
                        },
                        new
                        {
                            ID = 461,
                            Name = "Odense",
                            NationId = 0,
                            Population = 204895
                        },
                        new
                        {
                            ID = 479,
                            Name = "Svendborg",
                            NationId = 0,
                            Population = 58296
                        },
                        new
                        {
                            ID = 480,
                            Name = "Nordfyns",
                            NationId = 0,
                            Population = 29665
                        },
                        new
                        {
                            ID = 482,
                            Name = "Langeland",
                            NationId = 0,
                            Population = 12491
                        },
                        new
                        {
                            ID = 492,
                            Name = "Ærø",
                            NationId = 0,
                            Population = 5964
                        },
                        new
                        {
                            ID = 510,
                            Name = "Haderslev",
                            NationId = 0,
                            Population = 55670
                        },
                        new
                        {
                            ID = 530,
                            Name = "Billund",
                            NationId = 0,
                            Population = 26608
                        },
                        new
                        {
                            ID = 540,
                            Name = "Sønderborg",
                            NationId = 0,
                            Population = 74220
                        },
                        new
                        {
                            ID = 550,
                            Name = "Tønder",
                            NationId = 0,
                            Population = 37366
                        },
                        new
                        {
                            ID = 561,
                            Name = "Esbjerg",
                            NationId = 0,
                            Population = 115483
                        },
                        new
                        {
                            ID = 563,
                            Name = "Fanø",
                            NationId = 0,
                            Population = 3488
                        },
                        new
                        {
                            ID = 573,
                            Name = "Varde",
                            NationId = 0,
                            Population = 49961
                        },
                        new
                        {
                            ID = 575,
                            Name = "Vejen",
                            NationId = 0,
                            Population = 42742
                        },
                        new
                        {
                            ID = 580,
                            Name = "Aabenraa",
                            NationId = 0,
                            Population = 58761
                        },
                        new
                        {
                            ID = 607,
                            Name = "Fredericia",
                            NationId = 0,
                            Population = 51377
                        },
                        new
                        {
                            ID = 615,
                            Name = "Horsens",
                            NationId = 0,
                            Population = 90966
                        },
                        new
                        {
                            ID = 621,
                            Name = "Kolding",
                            NationId = 0,
                            Population = 93175
                        },
                        new
                        {
                            ID = 630,
                            Name = "Vejle",
                            NationId = 0,
                            Population = 115748
                        },
                        new
                        {
                            ID = 657,
                            Name = "Herning",
                            NationId = 0,
                            Population = 89127
                        },
                        new
                        {
                            ID = 661,
                            Name = "Holstebro",
                            NationId = 0,
                            Population = 58591
                        },
                        new
                        {
                            ID = 665,
                            Name = "Lemvig",
                            NationId = 0,
                            Population = 19722
                        },
                        new
                        {
                            ID = 671,
                            Name = "Struer",
                            NationId = 0,
                            Population = 21036
                        },
                        new
                        {
                            ID = 706,
                            Name = "Syddjurs",
                            NationId = 0,
                            Population = 42962
                        },
                        new
                        {
                            ID = 707,
                            Name = "Norddjurs",
                            NationId = 0,
                            Population = 37089
                        },
                        new
                        {
                            ID = 710,
                            Name = "Favrskov",
                            NationId = 0,
                            Population = 48397
                        },
                        new
                        {
                            ID = 727,
                            Name = "Odder",
                            NationId = 0,
                            Population = 22844
                        },
                        new
                        {
                            ID = 730,
                            Name = "Randers",
                            NationId = 0,
                            Population = 97805
                        },
                        new
                        {
                            ID = 740,
                            Name = "Silkeborg",
                            NationId = 0,
                            Population = 94026
                        },
                        new
                        {
                            ID = 741,
                            Name = "Samsø",
                            NationId = 0,
                            Population = 3657
                        },
                        new
                        {
                            ID = 746,
                            Name = "Skanderborg",
                            NationId = 0,
                            Population = 62678
                        },
                        new
                        {
                            ID = 751,
                            Name = "Aarhus",
                            NationId = 0,
                            Population = 349983
                        },
                        new
                        {
                            ID = 756,
                            Name = "Ikast-Brande",
                            NationId = 0,
                            Population = 41369
                        },
                        new
                        {
                            ID = 760,
                            Name = "Ringkøbing-Skjern",
                            NationId = 0,
                            Population = 56594
                        },
                        new
                        {
                            ID = 766,
                            Name = "Hedensted",
                            NationId = 0,
                            Population = 46722
                        },
                        new
                        {
                            ID = 773,
                            Name = "Morsø",
                            NationId = 0,
                            Population = 20247
                        },
                        new
                        {
                            ID = 779,
                            Name = "Skive",
                            NationId = 0,
                            Population = 45851
                        },
                        new
                        {
                            ID = 787,
                            Name = "Thisted",
                            NationId = 0,
                            Population = 43423
                        },
                        new
                        {
                            ID = 791,
                            Name = "Viborg",
                            NationId = 0,
                            Population = 96921
                        },
                        new
                        {
                            ID = 810,
                            Name = "Brønderslev",
                            NationId = 0,
                            Population = 36304
                        },
                        new
                        {
                            ID = 813,
                            Name = "Frederikshavn",
                            NationId = 0,
                            Population = 59654
                        },
                        new
                        {
                            ID = 820,
                            Name = "Vesthimmerlands",
                            NationId = 0,
                            Population = 36727
                        },
                        new
                        {
                            ID = 825,
                            Name = "Læsø",
                            NationId = 0,
                            Population = 1786
                        },
                        new
                        {
                            ID = 840,
                            Name = "Rebild",
                            NationId = 0,
                            Population = 30113
                        },
                        new
                        {
                            ID = 846,
                            Name = "Mariagerfjord",
                            NationId = 0,
                            Population = 41800
                        },
                        new
                        {
                            ID = 849,
                            Name = "Jammerbugt",
                            NationId = 0,
                            Population = 38324
                        },
                        new
                        {
                            ID = 851,
                            Name = "Aalborg",
                            NationId = 0,
                            Population = 217075
                        },
                        new
                        {
                            ID = 860,
                            Name = "Hjørring",
                            NationId = 0,
                            Population = 64483
                        });
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.Nation", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Nations");

                    b.HasData(
                        new
                        {
                            Name = "Danmark"
                        });
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.TestCenter", b =>
                {
                    b.Property<int>("TestCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CenterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CloseHour")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipalityID")
                        .HasColumnType("int");

                    b.Property<int>("OpenHour")
                        .HasColumnType("int");

                    b.HasKey("TestCenterId");

                    b.HasIndex("MunicipalityID");

                    b.ToTable("TestCenters");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.TestCenterManagement", b =>
                {
                    b.Property<int>("TestCenterManagementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("TestCenterId")
                        .HasColumnType("int");

                    b.HasKey("TestCenterManagementId");

                    b.HasIndex("TestCenterId")
                        .IsUnique();

                    b.ToTable("TestCenterManagements");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.TestDate", b =>
                {
                    b.Property<int>("TestDateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Citizen_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Result")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestCenterID")
                        .HasColumnType("int");

                    b.HasKey("TestDateID");

                    b.HasIndex("Citizen_ID");

                    b.HasIndex("TestCenterID");

                    b.ToTable("TestDates");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.Citizen", b =>
                {
                    b.HasOne("Covid19_Tracking.Domain.Municipality", "Municipality")
                        .WithMany("Citizens")
                        .HasForeignKey("MunicipalityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.CitizenLocation", b =>
                {
                    b.HasOne("Covid19_Tracking.Domain.Location", "Location")
                        .WithMany("CitizenLocations")
                        .HasForeignKey("Adresse");

                    b.HasOne("Covid19_Tracking.Domain.Citizen", "Citizen")
                        .WithMany("CitizenLocations")
                        .HasForeignKey("Citizen_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.Location", b =>
                {
                    b.HasOne("Covid19_Tracking.Domain.Municipality", "Municipality")
                        .WithMany("Locations")
                        .HasForeignKey("MunicipalityID");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.Municipality", b =>
                {
                    b.HasOne("Covid19_Tracking.Domain.Nation", "Nation")
                        .WithMany("Municipalities")
                        .HasForeignKey("Nation_Name");

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.TestCenter", b =>
                {
                    b.HasOne("Covid19_Tracking.Domain.Municipality", "Municipality")
                        .WithMany("TestCenters")
                        .HasForeignKey("MunicipalityID");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.TestCenterManagement", b =>
                {
                    b.HasOne("Covid19_Tracking.Domain.TestCenter", "TestCenter")
                        .WithOne("TestCenterManagement")
                        .HasForeignKey("Covid19_Tracking.Domain.TestCenterManagement", "TestCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCenter");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.TestDate", b =>
                {
                    b.HasOne("Covid19_Tracking.Domain.Citizen", "Citizen")
                        .WithMany("TestDates")
                        .HasForeignKey("Citizen_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Covid19_Tracking.Domain.TestCenter", "TestCenter")
                        .WithMany("TestDates")
                        .HasForeignKey("TestCenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("TestCenter");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.Citizen", b =>
                {
                    b.Navigation("CitizenLocations");

                    b.Navigation("TestDates");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.Location", b =>
                {
                    b.Navigation("CitizenLocations");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.Municipality", b =>
                {
                    b.Navigation("Citizens");

                    b.Navigation("Locations");

                    b.Navigation("TestCenters");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.Nation", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("Covid19_Tracking.Domain.TestCenter", b =>
                {
                    b.Navigation("TestCenterManagement");

                    b.Navigation("TestDates");
                });
#pragma warning restore 612, 618
        }
    }
}
